### ISSUE TITLE
Quality of authenticated streams?

### ISSUE THREAD

**Issue by 01tot10** [impliedchaos/mopidy-bandcamp#11]
Hey @impliedchaos!

First off, thanks SO MUCH for putting this together! This really connected the pieces for me, I've been using Mopidy for a couple of years, and not being able to play things off Bandcamp really made it a hassle for me sometimes. I just installed the plugin and tried adding my first album and it worked without any issues! Super awesome.

One question though - if you authenticate Bandcamp so that you'll be able to access your own collection, does it also mean you'll get the nice V0 streams, instead of the 128kbps ones [*]? I didn't find a mention of this in the documentation. Cheers, and looking forward to see progress on this!

[*] https://get.bandcamp.help/hc/en-us/articles/360007802334-What-format-quality-are-the-streams-on-Bandcamp-

**Comment by impliedchaos** [comment]
Yes it does, and thanks for pointing out the missing documentation.  I've add a small note about that to the readme.  Also, there was a recent change to bandcamp's JSON fomatting that I had to push a quick fix for as well so browsing your collections works again.  v1.1.4 has been released.

Thanks again!
