### ISSUE TITLE
 Bandcamp add uri from web Not working

### ISSUE THREAD

**Issue by afredsa** [impliedchaos/mopidy-bandcamp#15]
Hi,  I am not sure why I am seeing this and did not see another format to ask.  I am not sure it is an "issue".

**Problem summary:**
When I browse in a Mopidy Frontend, Bancamp ext will add the correct URI to the playlist.  
However, when using the Web Javascript (bookmark), or the 192.168.1.100:6680/bandcamp page to add, it results in a URI like:  bandcamp:track:None-3763840907-1951117791.  <note the None>

**More info:**
Both Chromium and Firefox.
Both The JavaScript or entering using the  6680:/bandcamp webpage.
URL pointing to either looback IP or local IP
Every bandcamp page tried has the same result of bandcam:track:None-<Correct Numbers from here>
JavaScript Bookmark URL:
```
javascript:s='http://192.168.1.100:6680/bandcamp/';f=document.createElement('form');f.action=s;i=document.createElement('input');i.type='hidden';i.name='url';i.value=window.location.href;f.appendChild(i);document.body.appendChild(f);f.submit();
```
**Example From Bandcamp track URL:** 
    https://jasonwebley.bandcamp.com/track/in-this-light

If using Mopidy Client Browse | Bandcamp the URI returned is:
**bandcamp:track:2220410354-3763840907-1951117791** 

However, Using the Bandcamp ext Webpage (or bookmark) the URI returned is:
**bandcamp:track:None-3763840907-1951117791**

**Steps and what is seen:**
Click the JavaScript Bookmark while on URL above:
Browser warning page shows up:
```
The information you’re about to submit is not secure
Because this form is being submitted using a connection that’s not secure, your information will be visible to others.
Click [Send Anyway]
```
Popup Dialog:  
```
  192.168.1.100:6680/ says
  URL has been added.
Click [OK]
```
**Back In Mopidy Client (IRIS) Now Playing:**
Track has been added to Queue.  
Shows All correct info. EG:
```
In This Light
Jason Webley . In This Light - Live at Bear Creek 4:04
```
In Mopidy Client (IRIS) the tracks will not play.   
Using the Client to see the URI with <Track Info> it will show: 
```
Error: Not found
Could not find anything with URI bandcamp:track:None-3763840907-1951117791

```
We can also use Copy/Paste URI to see the same bad URI above.   Used IRIS because other Front Ends like Musicbox_webclient and Muse have the same problem (as expected), but do not handle the bad URI in a way we can see it (both just fail to play, or will hang on tack info request).

**Mopidy/Extensions/Python/Etc Versions:**

```
Executable: /usr/bin/mopidy
Platform: Linux-5.10.35-v8+-aarch64-with-debian-10.9
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
---
Mopidy-Bandcamp: 1.1.4 from /usr/local/lib/python3.7/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  setuptools: 54.2.0 from /usr/local/lib/python3.7/dist-packages
---
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
  setuptools: 54.2.0 from /usr/local/lib/python3.7/dist-packages

```

**Comment by impliedchaos** [comment]
Hi, I just tried this on my end, and it's working (I know that is of absolutely no help to you 😉).  But I'm researching this now.  
Thanks for the excellently detailed bug report.  At first I assumed that you were using an older version, but nope, you're showing v1.1.4, so there's definitely something going wrong.

FYI, the web frontend is just prepending "bandcamp:" to the front of the url and adding that to the queue.  So you can also try this on the command line (if you have mpc installed) as:
```shell
$ mpc add "bandcamp:https://jasonwebley.bandcamp.com/track/in-this-light"
```
Which does the same thing as the web frontend.

There's code in the `scrape` method of the backend that specifically sets the band_id to "None" if it can't find it in data it scrapes from the page.  Now the question is why am I seeing the band_id, and you are not?

So here are my initial questions:

1. Is this album in your collection? 
2. Are you using a fan account, or an artist account (something that I never thought of until now)?

Thanks!

**Comment by afredsa** [comment]
Using mpc had the same effect.
I do not authenticate/login to bandcamp.  So I think the answer is no to your questions 1,2.

I tried to poke at the code, but  .py is not my native language and I do not have/know a dev env for debugging in py.  Reading the code I think I figured out the line where it yanks from but did not have a way to debug or explore the text (json?) it brings back...  Are there Docs somewhere for scrape?  Or a quick script to execute scrape interactively? ( As I said .py is not my native language and I was trying vscode or thony but did not get to the point of successfully instantiating bandcampclient.scrape (before I gave up ), mainly I could not see where "config" is set, and ran into a module error when import config from mopidy ).  Or????

Thanks

**Comment by impliedchaos** [comment]
> I do not authenticate/login to bandcamp. 

Ah ha!  That's it.   I've added the non-authenticated scrape to the unit tests (like it should have been in the first place), and it's breaking exactly as you described.  I'm working on the fix now, and will push out a new release once I'm done.

Thank you for finding this and pointing it out.

**Comment by impliedchaos** [comment]
OK, Can you upgrade to v1.1.5 and let me know if that solves the issue for you?

**Comment by afredsa** [comment]
That worked!

(After a bit of clearing caches :))

Thank you.   
A
