### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by mebitek** [impliedchaos/mopidy-bandcamp#18]
Just installed the plugin
all seems to work fine except images. where are they supposed to be stored?
seems that the method get_images is never called.
could you please help me to let it works? I'm using ncmpcpp

**Comment by orontee** [comment]
I don't know what is ncmpcpp but with clients like argos or iris images are fetched without any particular tweak... Works out of the box.

**Comment by mebitek** [comment]
thx for your answer, do you know if there is a location where artwork are stored locally?

**Comment by orontee** [comment]
> thx for your answer, do you know if there is a location where artwork are stored locally?

Mopidy-Bandcamp doesn't manage images; It sends URLs to Mopidy clients, each Mopidy client requests the images directly from those URLs and is free to cache images or not in whatever location it has access too.

**Comment by mebitek** [comment]
thx I figure out how to use, I wrote a python script with mopidy-async-client and now works great
thanks so much for your help
