### ISSUE TITLE
Pip install command

### ISSUE THREAD

**Issue by kingosticks** [impliedchaos/mopidy-bandcamp#2]
We'd suggest 
```
sudo python3 -m pip install Mopidy-Bandcamp
```
in the install instructions. I know pip for python2 was recently deprecated but it's going to be hang around for a long time and people copy and pasting the command will find it doesn't work.

**Comment by kingosticks** [comment]
Also, you don't *need* to add `enable = true` to your config as that is the default value.

**Comment by impliedchaos** [comment]
> I know pip for python2 was recently deprecated but it's going to be hang around for a long time and people copy and pasting the command will find it doesn't work.

Yeah,  I think I even use a pip3 alias for this.  BTW - these instructions were there from when I just lazily copy/pasted from:
https://docs.mopidy.com/en/latest/extensiondev/

> Also, you don't need to add enable = true to your config as that is the default value.

I feel incredibly stupid for not knowing this. It's even mentioned multiple times in the Mopidy documentation, but for some reason I convinced myself that this wasn't the case.

Thanks for pointing these out!

**Comment by kingosticks** [comment]
Ah thanks, looks like we didn't update that example there. The cookie cutter project should be updated to reflect our current best practices.

Cheers for this extension. I wish bandcamp would provide an API with support for playing my purchased songs, it's by far my preferred way to buy music these days. Every so often I take a look and there's still no sign. Shame.
